name: Cloudhub deployment with Maven
on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'uat'
    types:
      - closed
      
env:
 APP_NAME_DEV : "hls-fhir-to-x12-dev"
 ENVIRONMENT_DEV : "Sandbox"
 APP_NAME_UAT : "hls-fhir-to-x12-UAT"
 ENVIRONMENT_UAT : "UAT"


      
jobs:
  Sandbox-Development:
    if: ${{ github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-latest
    environment : dev
    steps:
    - name: Checkout repository  
      uses: actions/checkout@v2
    - name: Publish to Exchange
      run: mvn -s settings.xml clean deploy package -Denv=$ENVIRONMENT_DEV -DappName=$APP_NAME_DEV -Dreplicas=1 -DvCores=0.1 -DbusinessGroupId=${{ secrets.BUSINESSGROUPID }} -Danypoint_platform_client_id=${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID }} -Danypoint_platform_client_secret=${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }} -DconnectedAppClientId=${{ secrets.CONNECTEDAPPCLIENTID }} -DconnectedAppClientSecret=${{ secrets.CONNECTEDAPPCLIENTSECRET }} -Dtarget=${{ secrets.TARGET_SANDBOX}}
    - name: Deploying to Sandbox
      run: mvn -s settings.xml clean deploy package -Denv=$ENVIRONMENT_DEV -DmuleDeploy -DappName=$APP_NAME_DEV -Dreplicas=1 -DvCores=0.1 -DbusinessGroupId=${{ secrets.BUSINESSGROUPID }} -Danypoint_platform_client_id=${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID }} -Danypoint_platform_client_secret=${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }} -DconnectedAppClientId=${{ secrets.CONNECTEDAPPCLIENTID }} -DconnectedAppClientSecret=${{ secrets.CONNECTEDAPPCLIENTSECRET }} -Dtarget=${{ secrets.TARGET_SANDBOX}}
 
  Uat-Testing:
    if: ${{ github.ref == 'refs/heads/uat'}}
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2
    # Add your build, test, or other steps here
    # For example:
    - name: Run after merge steps
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.action }}" == "closed" ] && [ "${{ github.event.pull_request.merged }}" == "true" ]; then
         mvn -s settings.xml clean deploy package -Denv=$ENVIRONMENT_UAT -DappName=$APP_NAME_UAT -Dreplicas=${{ secrets.REPLICAS }} -DvCores=${{ secrets.VCORES }} -DbusinessGroupId=${{ secrets.BUSINESSGROUPID }} -Danypoint_platform_client_id=${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID }} -Danypoint_platform_client_secret=${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }} -DconnectedAppClientId=${{ secrets.CONNECTEDAPPCLIENTID }} -DconnectedAppClientSecret=${{ secrets.CONNECTEDAPPCLIENTSECRET }} -Dtarget=${{ secrets.TARGET_SANDBOX}}
         mvn -s settings.xml clean deploy package -Denv=$ENVIRONMENT_UAT -DmuleDeploy -DappName=$APP_NAME_UAT -Dreplicas=${{ secrets.REPLICAS }} -DvCores=${{ secrets.VCORES }} -DbusinessGroupId=${{ secrets.BUSINESSGROUPID }} -Danypoint_platform_client_id=${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID }} -Danypoint_platform_client_secret=${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }} -DconnectedAppClientId=${{ secrets.CONNECTEDAPPCLIENTID }} -DconnectedAppClientSecret=${{ secrets.CONNECTEDAPPCLIENTSECRET }} -Dtarget=${{ secrets.TARGET_SANDBOX}}
        fi
