name: Cloudhub deployment with Maven
on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'uat'
    types:
      - closed


      
jobs:
  Sandbox-Development:
    if: ${{ github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-latest
    environment : dev
    steps:
    - name: Checkout repository  
      uses: actions/checkout@v2
    - name: checking
      run : echo $TARGET_SANDBOX
    - name: Publish to Exchange
      run: mvn -s settings.xml clean deploy package -Denv=${{ vars.MULESOFT_ENVIRONMENT }} -DappName=${{ vars.APPNAME }} -Dreplicas=${{ vars.REPLICAS }} -DvCores=${{ vars.VCORES }} -DbusinessGroupId=${{ secrets.BUSINESSGROUPID }} -Danypoint_platform_client_id=${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID }} -Danypoint_platform_client_secret=${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }} -DconnectedAppClientId=${{ secrets.CONNECTEDAPPCLIENTID }} -DconnectedAppClientSecret=${{ secrets.CONNECTEDAPPCLIENTSECRET }} -Dtarget=${{ vars.TARGET }}
    - name: Deploying to Sandbox
      run: mvn -s settings.xml clean deploy package -Denv=${{ vars.MULESOFT_ENVIRONMENT }} -DmuleDeploy -DappName=${{ vars.APPNAME }} -Dreplicas=${{ vars.REPLICAS }} -DvCores=${{ vars.VCORES }} -DbusinessGroupId=${{ secrets.BUSINESSGROUPID }} -Danypoint_platform_client_id=${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID }} -Danypoint_platform_client_secret=${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }} -DconnectedAppClientId=${{ secrets.CONNECTEDAPPCLIENTID }} -DconnectedAppClientSecret=${{ secrets.CONNECTEDAPPCLIENTSECRET }} -Dtarget=${{ vars.TARGET }}
 
  Uat-Testing:
    if: ${{ github.ref == 'refs/heads/uat'}}
    runs-on: ubuntu-latest
    environment : uat
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v2
    # Add your build, test, or other steps here
    # For example:
    - name: Run after merge steps
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.action }}" == "closed" ] && [ "${{ github.event.pull_request.merged }}" == "true" ]; then
             mvn -s settings.xml clean deploy package -Denv=${{ vars.MULESOFT_ENVIRONMENT }} -DappName=${{ vars.APPNAME }} -Dreplicas=${{ vars.REPLICAS }} -DvCores=${{ vars.VCORES }} -DbusinessGroupId=${{ secrets.BUSINESSGROUPID }} -Danypoint_platform_client_id=${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID }} -Danypoint_platform_client_secret=${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }} -DconnectedAppClientId=${{ secrets.CONNECTEDAPPCLIENTID }} -DconnectedAppClientSecret=${{ secrets.CONNECTEDAPPCLIENTSECRET }} -Dtarget=${{ vars.TARGET }}
             mvn -s settings.xml clean deploy package -Denv=${{ vars.MULESOFT_ENVIRONMENT }} -DappName=${{ vars.APPNAME }} -Dreplicas=${{ vars.REPLICAS }} -DvCores=${{ vars.VCORES }} -DbusinessGroupId=${{ secrets.BUSINESSGROUPID }} -Danypoint_platform_client_id=${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID }} -Danypoint_platform_client_secret=${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }} -DconnectedAppClientId=${{ secrets.CONNECTEDAPPCLIENTID }} -DconnectedAppClientSecret=${{ secrets.CONNECTEDAPPCLIENTSECRET }} -Dtarget=${{ vars.TARGET }} -DmuleDeploy
        fi
