name: Cloudhub deployment with Maven
  
on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'uat'
    types:
      - closed

      
jobs:
  Sandbox-Development:
    if: ${{ github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-latest
    environment : dev
    steps:
    - name: Checkout repository  
      uses: actions/checkout@v2
    - name: checking
      run : echo ${{ secrets.APPNAME }}
    
